name: 'Build and Push'
description: 'Build the Docker image and push to GitHub Container Registry'
inputs:
  base_tag:
    description: 'The tag of the base image to use'
    required: true
    default: ''
  output_tag:
    description: 'The tag for the output image'
    required: true
    default: ''
  secret:
    description: 'GitHub Container Registry secret'
    required: true

runs:
  using: "composite"
  steps:
    - name: Parse inputs
      run: |
        BASE_TAG=${{ inputs.base_tag }}
        OUTPUT_TAG=${{ inputs.output_tag }}
        echo "::debug::Using base image tag ${BASE_TAG}"
        echo "BASE_TAG=${BASE_TAG}" >> $GITHUB_ENV
        IMAGE_NAME=component-sdk:${OUTPUT_TAG}
        echo "::debug::Generated image name will be ${IMAGE_NAME}"
        echo "IMAGE_NAME=${IMAGE_NAME}" >> $GITHUB_ENV
      shell: bash

    - name: Build image
      run: |
        IMAGE_NAME=${{ env.IMAGE_NAME }}
        docker build . \
          --build-arg BASE_TAG=${BASE_TAG} \
          --tag ${IMAGE_NAME}
      shell: bash

    - name: Login to GitHub Container Registry
      run: echo "${{ inputs.secret }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      shell: bash

    - name: Push image
      run: |
        IMAGE_NAME=${{ env.IMAGE_NAME }}
        docker tag ${IMAGE_NAME} ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
        docker push ghcr.io/${{ github.repository_owner }}/${IMAGE_NAME}
      shell: bash