name: Build and push tagged image

# Run workflow on new tags
on:
  release:
    types: [published]

jobs:

  build-publish-tagged-component-sdk:
    runs-on: ubuntu-latest
    name: Build and publish component-sdk image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Parse tag
        shell: bash
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          TAG="${TAG/\//-}"
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          base_tag: galactic
          output_tag: ${TAG}
          secret: ${{ secrets.GITHUB_TOKEN }}
