name: Build and push tagged image

# Run workflow on new tags
on:
  release:
    types: [published]

jobs:

  build-publish-tagged-component-sdk:
    runs-on: ubuntu-latest
    name: Build and publish component-sdk image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Parse tag
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          TAG="${TAG/\//-}"
          echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Build and Push
        uses: ./.github/actions/build-push-multi-arch
        with:
          base_tag: humble
          output_tag: ${{ env.TAG }}
          secret: ${{ secrets.GITHUB_TOKEN }}
