name: Build and push multi-arch images

# Run workflow on push to develop branch
on:
  push:
    branches:
      - develop

env:
  CI_BRANCH: 'ci'

jobs:

  create-new-ci-branch:
    runs-on: ubuntu-latest
    name: Create new ci branch from develop
    outputs:
      latest_hash: ${{ steps.recreate.outputs.latest_hash }}
      devel_hash: ${{ steps.recreate.outputs.devel_hash }}
      ci_branch: ${{ steps.recreate.outputs.ci_branch }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Recreate ci branch
        id: recreate
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
          BRANCH=${{ env.CI_BRANCH }}
          git checkout -b ${BRANCH} origin/develop && git push -f -u origin ${BRANCH}
          echo "ci_branch=${BRANCH}" >> $GITHUB_OUTPUT
          
          curl -o ros2-modulo-humble-hash https://raw.githubusercontent.com/aica-technology/docker-images/ci/ros2_modulo/humble-hash
          HASH=$(cat ./ros2-modulo-humble-hash || echo '')
          echo "latest_hash=${HASH}" >> $GITHUB_OUTPUT
          
          curl -o ros2-modulo-humble-devel-hash https://raw.githubusercontent.com/aica-technology/docker-images/ci/ros2_modulo/humble-devel-hash
          HASH=$(cat ./ros2-modulo-humble-devel-hash || echo '')
          echo "devel_hash=${HASH}" >> $GITHUB_OUTPUT

  build-publish-latest:
    needs: create-new-ci-branch
    uses: aica-technology/.github/.github/workflows/build-push-multi-arch.yml@ed4ba3f4327b2a61948cde7b4e9410363114c478
    name: Build and publish latest component-sdk image
    with:
      image_name: ${{ github.repository }}
      image_tags: latest
      build_context_path: .
      dockerfile_path: Dockerfile
      platforms: linux/amd64,linux/arm64
      build_flags: '--build-arg BASE_TAG=humble'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-publish-devel:
    needs: create-new-ci-branch
    uses: aica-technology/.github/.github/workflows/build-push-multi-arch.yml@ed4ba3f4327b2a61948cde7b4e9410363114c478
    name: Build and publish devel component-sdk image
    with:
      image_name: ${{ github.repository }}
      image_tags: devel
      build_context_path: .
      dockerfile_path: Dockerfile
      platforms: linux/amd64,linux/arm64
      build_flags: '--build-arg BASE_TAG=humble-devel'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  write-latest-hash:
    needs: [ create-new-ci-branch, build-publish-latest ]
    uses: aica-technology/.github/.github/workflows/write-file.yml@ed4ba3f4327b2a61948cde7b4e9410363114c478
    name: Write ros2-modulo:humble hash to file
    with:
      content: ${{ needs.create-new-ci-branch.outputs.latest_hash }}
      filepath: ./humble-hash
      branch: ${{ needs.create-new-ci-branch.outputs.ci_branch }}

  write-devel-hash:
    needs: [ create-new-ci-branch, build-publish-devel ]
    uses: aica-technology/.github/.github/workflows/write-file.yml@ed4ba3f4327b2a61948cde7b4e9410363114c478
    name: Write ros2-modulo:humble-devel hash to file
    with:
      content: ${{ needs.create-new-ci-branch.outputs.devel_hash }}
      filepath: ./humble-devel-hash
      branch: ${{ needs.create-new-ci-branch.outputs.ci_branch }}
