name: Build and push 'latest' image

# Run workflow on push to develop branch
on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:

  build-publish-latest-component-sdk:
    runs-on: ubuntu-latest
    name: Build and publish component-sdk image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push
        uses: ./.github/actions/build-push
        with:
          base_tag: galactic
          output_tag: latest
          secret: ${{ secrets.GITHUB_TOKEN }}
