name: Check for updated upstream images

# Run scheduled workflow
on:
  schedule:
    - cron: '00 5 * * MON'
  workflow_dispatch:

env:
  CI_BRANCH: 'ci'

jobs:

  check-hash:
    runs-on: ubuntu-latest
    name: Check hashes of ros2-modulo images
    outputs:
      latest_hash: ${{ steps.check-humble.outputs.id }}
      devel_hash: ${{ steps.check-humble-devel.outputs.id }}
      ci_branch: ${{ steps.ci-branch.outputs.ci_branch }}
    steps:
      - name: Checkout CI branch
        uses: actions/checkout@v3
        with:
          ref: ${{ env.CI_BRANCH }}

      - name: Export ci branch
        id: ci-branch
        run: BRANCH=${{ env.CI_BRANCH }} && echo "ci_branch=${BRANCH}" >> $GITHUB_OUTPUT

      - name: Check hash of ros2-modulo:humble image
        id: check-humble
        run: |
          curl -o ros2-modulo-humble-hash https://raw.githubusercontent.com/aica-technology/docker-images/ci/ros2_modulo/humble-hash
          NEW_HASH=$(cat ./ros2-modulo-humble-hash || echo '')
          OLD_HASH=$(cat ./humble-hash || echo '')
          if [ "${NEW_HASH}" = "${OLD_HASH}" ]; then
            echo "The ros2-modulo:humble image did not change."
          else
            echo "ros2-modulo:humble image has been updated, rebuilding image now..."
            echo "id=${NEW_HASH}" >> $GITHUB_OUTPUT
          fi

      - name: Check latest hash on ros2-modulo:humble-devel image
        id: check-humble-devel
        run: |
          curl -o ros2-modulo-humble-devel-hash https://raw.githubusercontent.com/aica-technology/docker-images/ci/ros2_modulo/humble-devel-hash
          NEW_HASH=$(cat ./ros2-modulo-humble-devel-hash || echo '')
          OLD_HASH=$(cat ./humble-devel-hash || echo '')
          if [ "${NEW_HASH}" = "${OLD_HASH}" ]; then
            echo "The ros2-modulo:humble-devel image did not change."
          else
            echo "ros2-modulo:humble-devel image has been updated, rebuilding image now..."
            echo "id=${NEW_HASH}" >> $GITHUB_OUTPUT
          fi

  build-publish-latest:
    needs: check-hash
    if: needs.check-hash.outputs.latest_hash
    uses: aica-technology/.github/.github/workflows/build-push-multi-arch.yml@v0.1
    name: Build and publish latest component-sdk image
    with:
      image_name: ${{ github.repository }}
      image_tags: latest
      platforms: linux/amd64,linux/arm64
      build_flags: '--build-arg BASE_TAG=humble'
      checkout_ref: develop
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build-publish-devel:
    needs: check-hash
    if: needs.check-hash.outputs.devel_hash
    uses: aica-technology/.github/.github/workflows/build-push-multi-arch.yml@v0.1
    name: Build and publish devel component-sdk image
    with:
      image_name: ${{ github.repository }}
      image_tags: devel
      platforms: linux/amd64,linux/arm64
      build_flags: '--build-arg BASE_TAG=humble-devel'
      checkout_ref: develop
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  write-latest-hash:
    needs: [ check-hash, build-publish-latest ]
    uses: aica-technology/.github/.github/workflows/write-file.yml@v0.1
    name: Write ros2-modulo:humble hash to file
    with:
      content: ${{ needs.check-hash.outputs.latest_hash }}
      filepath: ./humble-hash
      branch: ${{ needs.check-hash.outputs.ci_branch }}

  write-devel-hash:
    needs: [ check-hash, build-publish-devel ]
    uses: aica-technology/.github/.github/workflows/write-file.yml@v0.1
    name: Write ros2-modulo:humble-devel hash to file
    with:
      content: ${{ needs.check-hash.outputs.devel_hash }}
      filepath: ./humble-devel-hash
      branch: ${{ needs.check-hash.outputs.ci_branch }}
