name: Manual build and push

# Run workflow by manual dispatch
on:
  workflow_dispatch:
    inputs:
      base_tag:
        description: 'The tag of the base image to use'
        required: true
        type: string
      output_tag:
        description: 'The tag for the output image'
        required: true
        type: string

jobs:
  build-publish:
    uses: aica-technology/.github/.github/workflows/build-push-multi-arch.yml@v0.1
    name: Build and publish image
    with:
      image_name: ${{ github.repository }}
      image_tags: ${{ inputs.output_tag }}
      platforms: linux/amd64,linux/arm64
      build_flags: '--build-arg BASE_TAG=${{ inputs.base_tag }}'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}